# Generated by Django 5.2.7 on 2025-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avalibilty',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
