# Generated by Django 5.2.7 on 2025-10-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor_avalibilty_doctor_patient_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patient_number',
        ),
    ]
