# Generated by Django 5.2.7 on 2025-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doctor_patient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
