# Generated by Django 5.2.7 on 2025-10-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='avalibilty',
            new_name='availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
