# Generated by Django 5.2.7 on 2025-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_avalibilty_doctor_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.CharField(default='Available', max_length=255),
        ),
    ]
